# Dockerfile
FROM postgres:latest

RUN mkdir -p /tmp/psql_data/

COPY rates.sql /tmp/psql_data/
COPY init_docker_postgres.sh /docker-entrypoint-initdb.d/

COPY health_check.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/health_check.sh

HEALTHCHECK CMD /usr/local/bin/health_check.sh